# Generated by Django 5.1.1 on 2024-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_russian', models.CharField(max_length=100)),
                ('word_in_hebrew', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='memory_cards/images/')),
                ('pronunciation', models.FileField(upload_to='memory_cards/pronunciation')),
            ],
        ),
    ]
